import = [
    "~/.config/alacritty/themes/themes/citylights.toml"
]

[shell]
program = "/bin/bash"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "None"
padding = {x = 7, y = 7}

[font]
size = 11
normal = {family = "JetBrainsMonoNL Nerd Font", style="Regular"}
bold = {family = "JetBrainsMonoNL Nerd Font", style="Bold"}
italic = {family = "JetBrainsMonoNL Nerd Font", style="Italic"}
bold_italic = {family = "JetBrainsMonoNL Nerd Font", style="Bold Italic"}
